export { Consul as default, Consul } from "./consul.js";
export type {
  CommonOptions,
  ConsulOptions,
  QueryMeta,
  ResponseResult,
} from "./consul.js";
export type {
  ConfigEntry,
  IntentionHTTPHeader,
  IntentionHTTPPermission,
  IntentionJWTRequirement,
  IntentionPermission,
  IntentionSource,
  ServiceIntentionsEntry,
  ServiceDefaultsEntry,
  ProxyDefaultsEntry,
  ServiceProtocol,
} from "./config.js";
export type {
  Operation as TransactionOperation,
  CreateResult as TransactionCreateResult,
  TransactionResult,
  TransactionError,
} from "./transaction.js";
export type {
  AclLink,
  AclServiceIdentity,
  AclNodeIdentity,
  AclTemplatedPolicy,
  AclTokenEntry,
  AclTokenUpdateEntry,
  AclTokenResult,
  AclTokenListResult,
  AclTokenExpandedResult,
  AclTokenListOptions,
  AclPolicyEntry,
  AclPolicyResult,
  AclPolicyListResult,
  AclRoleEntry,
  AclRoleResult,
  AclJsonValue,
  AclAuthMethodEntry,
  AclAuthMethodUpdateEntry,
  AclAuthMethodResult,
  AclAuthMethodListResult,
  AclBindingRuleEntry,
  AclBindingRuleUpdateEntry,
  AclBindingRuleResult,
} from "./acl/modern.js";
